fconc: main.o doWrite.o write_file.o
	gcc -Wall -o fconc main.o doWrite.o write_file.o

main.o: main.c
	gcc -Wall -c main.c

doWrite.o: doWrite.c
	gcc -Wall -c doWrite.c

write_file.o: write_file.c
	gcc -Wall -c write_file.c
